create table "public"."cut" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "owner_fid" bigint not null,
    "parent_hash" text not null,
    "title" text,
    "tag" text,
    "img_url" text not null
);


alter table "public"."cut" enable row level security;

CREATE UNIQUE INDEX cut_pkey ON public.cut USING btree (id);

alter table "public"."cut" add constraint "cut_pkey" PRIMARY KEY using index "cut_pkey";


