create table "public"."bookmark" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "owner_fid" bigint not null,
    "saved_hash" text not null,
    "title" text not null,
    "tag" text
);


alter table "public"."bookmark" enable row level security;

CREATE UNIQUE INDEX bookmark_pkey ON public.bookmark USING btree (id);

alter table "public"."bookmark" add constraint "bookmark_pkey" PRIMARY KEY using index "bookmark_pkey";


